server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # No servir archivos internos
    location ~ /\. { deny all; }
    location ^~ /_backups/ { return 404; }
    location = /docker-compose.yml { return 404; }
    location = /nginx.conf { return 404; }
    location = /README.md { return 404; }
    location = /.env { return 404; }

    location / {
        try_files $uri $uri/ =404;
    }
}
